import { Job } from '../src/types.js';

const mockJobsBase: Partial<Job>[] = [
  {
    id: `mock-naukri-1`,
    title: 'Digital Marketing Manager',
    company: 'GrowthGenius India',
    location: 'Bangalore',
    experienceRequired: '4-7 years',
    salaryRange: '₹12,00,000 - ₹18,00,000',
    workMode: 'Hybrid',
    description: 'We are seeking a results-driven Digital Marketing Manager to lead our performance marketing and SEO initiatives. You will manage a team of 3 and oversee campaigns across Google Ads, Meta, and LinkedIn.',
    url: 'https://naukri.com/mock-1',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 2,
  },
  {
    id: `mock-naukri-2`,
    title: 'SEO Specialist',
    company: 'TechElevate',
    location: 'Remote',
    experienceRequired: '2-4 years',
    salaryRange: '₹6,00,000 - ₹10,00,000',
    workMode: 'Remote',
    description: 'Join our marketing team to optimize our B2B SaaS platform for organic search. You must have strong experience with Ahrefs, SEMrush, and technical SEO audits.',
    url: 'https://naukri.com/mock-2',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 5,
  },
  {
    id: `mock-naukri-3`,
    title: 'Content Marketing Manager',
    company: 'SaaSFlow',
    location: 'Pune',
    experienceRequired: '3-6 years',
    salaryRange: '₹10,00,000 - ₹15,00,000',
    workMode: 'On-site',
    description: 'Looking for a creative Content Marketing Manager to drive our content strategy, manage the blog, and create compelling case studies for our enterprise clients.',
    url: 'https://naukri.com/mock-3',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 1,
  },
  {
    id: `mock-naukri-4`,
    title: 'Performance Marketing Executive',
    company: 'RetailBoost',
    location: 'Mumbai',
    experienceRequired: '1-3 years',
    salaryRange: '₹5,00,000 - ₹8,00,000',
    workMode: 'Hybrid',
    description: 'Manage our paid acquisition channels. Optimize ROI on Google Ads and Facebook Ads. Ideal for someone with a strong analytical mindset and data-driven approach.',
    url: 'https://naukri.com/mock-4',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 4,
  },
  {
    id: `mock-naukri-5`,
    title: 'B2B Marketing Lead',
    company: 'EnterpriseSolutions',
    location: 'Gurgaon',
    experienceRequired: '6-9 years',
    salaryRange: '₹18,00,000 - ₹25,00,000',
    workMode: 'Hybrid',
    description: 'Lead our B2B marketing efforts. You will be responsible for lead generation, account-based marketing (ABM), and aligning marketing efforts with the sales team.',
    url: 'https://naukri.com/mock-5',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 10,
  },
  {
    id: `mock-naukri-6`,
    title: 'Marketing Analytics Specialist',
    company: 'DataDriven Corp',
    location: 'Remote',
    experienceRequired: '3-5 years',
    salaryRange: '₹14,00,000 - ₹20,00,000',
    workMode: 'Remote',
    description: 'Turn marketing data into actionable insights. Must be proficient in Google Analytics 4, Tag Manager, SQL, and creating dashboards in Looker Studio or Tableau.',
    url: 'https://naukri.com/mock-6',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 3,
  },
  {
    id: `mock-naukri-7`,
    title: 'Social Media Manager',
    company: 'ViralWave',
    location: 'Bangalore',
    experienceRequired: '2-5 years',
    salaryRange: '₹7,00,000 - ₹12,00,000',
    workMode: 'Hybrid',
    description: 'Own our social media presence across Instagram, Twitter, and LinkedIn. Create engaging content calendars and run community-building initiatives.',
    url: 'https://naukri.com/mock-7',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 7,
  },
  {
    id: `mock-naukri-8`,
    title: 'Email Marketing Specialist',
    company: 'InboxSuccess',
    location: 'Noida',
    experienceRequired: '2-4 years',
    salaryRange: '₹5,50,000 - ₹9,00,000',
    workMode: 'On-site',
    description: 'Manage end-to-end email campaigns. A/B testing, list segmentation, and improving open and click-through rates. Experience with Mailchimp or HubSpot required.',
    url: 'https://naukri.com/mock-8',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 6,
  },
  {
    id: `mock-naukri-9`,
    title: 'Growth Hacker',
    company: 'ScaleUp Startup',
    location: 'Remote',
    experienceRequired: '3-6 years',
    salaryRange: '₹15,00,000 - ₹22,00,000',
    workMode: 'Remote',
    description: 'Experiment rapidly across the funnel (AARRR) to drive user acquisition and retention. A mix of marketing, product, and data analysis skills required.',
    url: 'https://naukri.com/mock-9',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 1,
  },
  {
    id: `mock-naukri-10`,
    title: 'Director of Marketing',
    company: 'FinTech Innovations',
    location: 'Mumbai',
    experienceRequired: '10+ years',
    salaryRange: '₹35,00,000 - ₹50,00,000',
    workMode: 'Hybrid',
    description: 'Lead the entire marketing function including brand, performance, product marketing, and communications. Manage a budget of $5M+.',
    url: 'https://naukri.com/mock-10',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 12,
  },
];

// Adding some non-marketing roles to ensure our search doesn't return unrelated roles
export const mockJobs: Partial<Job>[] = [
  ...mockJobsBase,
  {
    id: `mock-naukri-11`,
    title: 'Senior Frontend Developer',
    company: 'WebTech Inc',
    location: 'Remote',
    experienceRequired: '5-8 years',
    salaryRange: '₹20,00,000 - ₹30,00,000',
    workMode: 'Remote',
    description: 'Looking for a React expert to build our next-generation UI. Must have experience with TypeScript, Vite, and state management.',
    url: 'https://naukri.com/mock-11',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 2,
  },
  {
    id: `mock-naukri-12`,
    title: 'Full Stack Engineer',
    company: 'Backend Systems',
    location: 'Bangalore',
    experienceRequired: '3-6 years',
    salaryRange: '₹15,00,000 - ₹25,00,000',
    workMode: 'Hybrid',
    description: 'Work on our core APIs and internal dashboards. Node.js, Express, PostgreSQL, and React experience is mandatory.',
    url: 'https://naukri.com/mock-12',
    source: 'Naukri (Mock)',
    postedDate: Date.now() - 86400000 * 1,
  }
];
