import { Job } from '../src/types.js';

const mockJobsBase: Partial<Job>[] = [
  {
    id: `mock-job-1`,
    title: 'Digital Marketing Manager',
    company: 'GrowthGenius',
    location: 'Bangalore',
    experienceRequired: '4-7 years',
    salaryRange: '₹12,00,000 - ₹18,00,000',
    workMode: 'Hybrid',
    description: 'We are seeking a results-driven Digital Marketing Manager to lead our performance marketing and SEO initiatives. You will manage campaigns across search, social, and professional networks.',
    url: 'https://example.com/jobs/1',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 2,
  },
  {
    id: `mock-job-2`,
    title: 'SEO Specialist',
    company: 'TechElevate',
    location: 'Remote',
    experienceRequired: '2-4 years',
    salaryRange: '₹6,00,000 - ₹10,00,000',
    workMode: 'Remote',
    description: 'Join our marketing team to optimize our B2B SaaS platform for organic search. Strong experience with technical SEO audits required.',
    url: 'https://example.com/jobs/2',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 5,
  },
  {
    id: `mock-job-3`,
    title: 'Content Marketing Manager',
    company: 'SaaSFlow',
    location: 'Pune',
    experienceRequired: '3-6 years',
    salaryRange: '₹10,00,000 - ₹15,00,000',
    workMode: 'On-site',
    description: 'Looking for a creative Content Marketing Manager to drive content strategy, manage editorial calendars, and craft client case studies.',
    url: 'https://example.com/jobs/3',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 1,
  },
  {
    id: `mock-job-4`,
    title: 'Performance Marketing Executive',
    company: 'RetailBoost',
    location: 'Mumbai',
    experienceRequired: '1-3 years',
    salaryRange: '₹5,00,000 - ₹8,00,000',
    workMode: 'Hybrid',
    description: 'Manage paid acquisition channels. Optimize ROI across digital ad networks with an analytical, data-driven approach.',
    url: 'https://example.com/jobs/4',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 4,
  },
  {
    id: `mock-job-5`,
    title: 'B2B Marketing Lead',
    company: 'EnterpriseSolutions',
    location: 'Gurgaon',
    experienceRequired: '6-9 years',
    salaryRange: '₹18,00,000 - ₹25,00,000',
    workMode: 'Hybrid',
    description: 'Lead B2B marketing initiatives, demand generation, and account-based marketing in alignment with sales leaders.',
    url: 'https://example.com/jobs/5',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 10,
  },
  {
    id: `mock-job-6`,
    title: 'Marketing Analytics Specialist',
    company: 'DataDriven Corp',
    location: 'Remote',
    experienceRequired: '3-5 years',
    salaryRange: '₹14,00,000 - ₹20,00,000',
    workMode: 'Remote',
    description: 'Turn marketing data into actionable insights. Proficient in web analytics, SQL, and business intelligence reporting.',
    url: 'https://example.com/jobs/6',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 3,
  },
  {
    id: `mock-job-7`,
    title: 'Social Media Manager',
    company: 'ViralWave',
    location: 'Bangalore',
    experienceRequired: '2-5 years',
    salaryRange: '₹7,00,000 - ₹12,00,000',
    workMode: 'Hybrid',
    description: 'Lead our social media engagement, brand presence, and community growth initiatives across professional channels.',
    url: 'https://example.com/jobs/7',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 7,
  },
  {
    id: `mock-job-8`,
    title: 'Email Marketing Specialist',
    company: 'InboxSuccess',
    location: 'Noida',
    experienceRequired: '2-4 years',
    salaryRange: '₹5,50,000 - ₹9,00,000',
    workMode: 'On-site',
    description: 'Manage end-to-end email campaigns, lifecycle marketing, list segmentation, and automated nurturing funnels.',
    url: 'https://example.com/jobs/8',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 6,
  },
  {
    id: `mock-job-9`,
    title: 'Growth Hacker',
    company: 'ScaleUp Startup',
    location: 'Remote',
    experienceRequired: '3-6 years',
    salaryRange: '₹15,00,000 - ₹22,00,000',
    workMode: 'Remote',
    description: 'Experiment rapidly across the funnel to drive acquisition, activation, and retention.',
    url: 'https://example.com/jobs/9',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 1,
  },
  {
    id: `mock-job-10`,
    title: 'Director of Marketing',
    company: 'FinTech Innovations',
    location: 'Mumbai',
    experienceRequired: '10+ years',
    salaryRange: '₹35,00,000 - ₹50,00,000',
    workMode: 'Hybrid',
    description: 'Lead the entire marketing function including brand, performance, product marketing, and communications.',
    url: 'https://example.com/jobs/10',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 12,
  },
];

export const mockJobs: Partial<Job>[] = [
  ...mockJobsBase,
  {
    id: `mock-job-11`,
    title: 'Senior Frontend Developer',
    company: 'WebTech Inc',
    location: 'Remote',
    experienceRequired: '5-8 years',
    salaryRange: '₹20,00,000 - ₹30,00,000',
    workMode: 'Remote',
    description: 'Looking for a React expert to build our next-generation UI. Must have experience with TypeScript, Vite, and modern front-end architecture.',
    url: 'https://example.com/jobs/11',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 2,
  },
  {
    id: `mock-job-12`,
    title: 'Full Stack Engineer',
    company: 'Backend Systems',
    location: 'Bangalore',
    experienceRequired: '3-6 years',
    salaryRange: '₹15,00,000 - ₹25,00,000',
    workMode: 'Hybrid',
    description: 'Work on core APIs, microservices, and web dashboards. Node.js, Express, and React experience required.',
    url: 'https://example.com/jobs/12',
    source: 'Demo',
    postedDate: Date.now() - 86400000 * 1,
  }
];
